{
  "Uuid": "b7e8b922-6c34-4563-a1a0-0fdf2295b90b",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Line.BottomPoint",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "8bce02c9d6c4426d836c1354c99fce9e",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "31336b00f6f64bf99ea7d86b9d3fe9ff",
          "Name": "startPoint",
          "Description": "Line start point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4aff9abfe4ae4de9a6db0e96263c87bb",
          "Name": "endPoint",
          "Description": "Line end point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "836085554b204cec8405d6e16ef2ceb4",
          "Name": "Line",
          "Description": "Line from start and end point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "a4b691be8f334a2685fe775a1c1eaf76",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "eeb22e84c7fd4b04bc53f9b620ffddf3",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "83e78c8facf149ef91207b06900a6e9b",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f78d3aeb4be444c4add09465ae8ac8fc",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "5abdd0d938e649e8b0c801af780cead2",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "94ec50c0ca44409695d8296ec2d70993",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "3de460179d764a85a55c21b89f90c05a",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a310d36c1f6d46669a1e17341ea0b6e8",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "46606c7fa8f241e6861a37311a651bbd",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "44321aaa57c34aaaaace5c185e97a746",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "Id": "4e720c3e55ca47faa9e5217184057d25",
      "NodeType": "CodeBlockNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "d90453040ab9426da3700562b3a1ec19",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly",
      "Code": "10;"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "bd1625b7ce77470a9f39961ce9c5939d",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "ab9d1900c554474e95ef4d6c59ef5d4d",
          "Name": "line",
          "Description": "the line to get\n\nLine",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "46da3a77a1384479ba55079ea2055be4",
          "Name": "point",
          "Description": "bottom point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "OpenMEPSandbox.Geometry.Line.BottomPoint@Autodesk.DesignScript.Geometry.Line",
      "Replication": "Auto",
      "Description": "get bottom point of line\n\nLine.BottomPoint (line: Line): Point"
    }
  ],
  "Connectors": [
    {
      "Start": "836085554b204cec8405d6e16ef2ceb4",
      "End": "ab9d1900c554474e95ef4d6c59ef5d4d",
      "Id": "5aee42e190ea4d47846ca06da3765d5f",
      "IsHidden": "False"
    },
    {
      "Start": "5abdd0d938e649e8b0c801af780cead2",
      "End": "31336b00f6f64bf99ea7d86b9d3fe9ff",
      "Id": "9647e43d2ffc40a7b147f1c80eb78f9f",
      "IsHidden": "False"
    },
    {
      "Start": "44321aaa57c34aaaaace5c185e97a746",
      "End": "4aff9abfe4ae4de9a6db0e96263c87bb",
      "Id": "3843280560db4c16b94aa8a055f243fb",
      "IsHidden": "False"
    },
    {
      "Start": "d90453040ab9426da3700562b3a1ec19",
      "End": "3de460179d764a85a55c21b89f90c05a",
      "Id": "66c5f5b7c3b149f0a60ee6d4150bb5e5",
      "IsHidden": "False"
    },
    {
      "Start": "d90453040ab9426da3700562b3a1ec19",
      "End": "a310d36c1f6d46669a1e17341ea0b6e8",
      "Id": "466a2582607d4b7d8700f49ff7adbe82",
      "IsHidden": "False"
    },
    {
      "Start": "d90453040ab9426da3700562b3a1ec19",
      "End": "46606c7fa8f241e6861a37311a651bbd",
      "Id": "45f79686a67549aabb7cf76d0d7d8ac6",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "OpenMEP",
      "Version": "1.0.0",
      "ReferenceType": "Package",
      "Nodes": [
        "bd1625b7ce77470a9f39961ce9c5939d"
      ]
    }
  ],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.18",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.18.0.2986",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "8bce02c9d6c4426d836c1354c99fce9e",
        "Name": "Line.ByStartPointEndPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 541.6,
        "Y": 320.80000000000007
      },
      {
        "Id": "a4b691be8f334a2685fe775a1c1eaf76",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 179.20000000000005,
        "Y": 183.2
      },
      {
        "Id": "94ec50c0ca44409695d8296ec2d70993",
        "Name": "Point.ByCoordinates",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 216.80000000000007,
        "Y": 411.2
      },
      {
        "Id": "4e720c3e55ca47faa9e5217184057d25",
        "Name": "Code Block",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -12.0,
        "Y": 469.0
      },
      {
        "Id": "bd1625b7ce77470a9f39961ce9c5939d",
        "Name": "Line.BottomPoint",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 870.1800756888631,
        "Y": 406.88497942652219
      }
    ],
    "Annotations": [],
    "X": 220.76458608355904,
    "Y": 42.235128132697184,
    "Zoom": 0.82770257044119022
  }
}